https://github.com/indication/OpenRedmine/issues/190<td class="d-block comment-body markdown-body  js-comment-body">

          <p>In Redmine 3 with OpenRedmine v3.19[52] doing a POST to modify or create a issue: "Something with wrong with connection. Try later."</p>
<p>Logs in server:</p>
<pre><code>==&gt; /var/log/httpd/error_log &lt;==
App 11254 stderr: 
App 11254 stderr: ActiveRecord::RecordNotFound (Couldn't find Tracker with id=8 [WHERE `projects_trackers`.`project_id` = 7]):
App 11254 stderr:   app/controllers/issues_controller.rb:425:in `build_new_issue_from_params'
App 11254 stderr: 
App 11254 stderr: 

==&gt; /var/log/httpd/ssl-access.log &lt;==
192.168.32.134 - - [28/Aug/2016:23:31:42 +0200] "POST /issues.xml HTTP/1.1" 404 459 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; XT894 Build/KTU84Q)"

</code></pre>
<p>Tested in apt-getable redmine in Debian Jessie and CentOS 7 downloading redmine from web using passenger.</p>
<p>Do you know what could happen?</p>
<p>Thank you</p>
      </td>